# Artificial Neural Networks (ANN) for Classification

**Importing the libraries**

In [45]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [46]:
tf.__version__

'1.14.0'

# 1. Data Preprocessing

**Importing Dataset**

In [34]:
dataset = pd.read_csv("./Data/Churn_Modelling.csv")
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [35]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

**Encoding categorical data**
- **Label Encoding the "Gender" column**

In [36]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


- **One Hot Encoding the "Geography" column**

In [38]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
X = ct.fit_transform(X)

In [40]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


**Splitting the dataset into the Training set and Test set**

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state = 0)

**Feature Scaling**<br>
<i><u>Note</u>: Feature Scaling is mandatory for Neural Networks.</i>

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# 2. Building the ANN

**Initializing the ANN**

In [53]:
ann = tf.keras.models.Sequential()

**Adding the input layer and the first hidden layer**

In [55]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

**Adding the second hidden layer**

In [57]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

**Adding the output layer**

In [58]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# 3. Training the ANN

**Compiling the ANN**

In [61]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

**Training the ANN on the Training set**

In [62]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
8000/8000 [==============================] - 1s 98us/sample - loss: 0.7310 - acc: 0.5216
Epoch 2/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.4882 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.4374 - acc: 0.8140
Epoch 4/100
8000/8000 [==============================] - 1s 102us/sample - loss: 0.4237 - acc: 0.8202
Epoch 5/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.4063 - acc: 0.8273
Epoch 6/100
8000/8000 [==============================] - 1s 87us/sample - loss: 0.3870 - acc: 0.8351
Epoch 7/100
8000/8000 [==============================] - 1s 80us/sample - loss: 0.3730 - acc: 0.8453
Epoch 8/100
8000/8000 [==============================] - 1s 88us/sample - loss: 0.3646 - acc: 0.8491
Epoch 9/100
8000/8000 [==============================] - 1s 82us/sample - loss: 0.3598 - acc: 0.8

# 4. Making the predictions and evaluating the model

**Predicting the result of a single observation**<br>
<pre>
Use our ANN model to predict if the customer with the following informations will leave the bank: 
Geography: France
Credit Score: 600
Gender: Male
Age: 40 years old
Tenure: 3 years
Balance: $ 60000
Number of Products: 2
Does this customer have a credit card? Yes
Is this customer an Active Member: Yes
Estimated Salary: $ 50000

So, should we say goodbye to that customer?
</pre>

In [66]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank.<br>
<u>Note 1</u>:<br>Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.<br>

<u>Note 2</u>:<br>Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

**Predicting the Test set results**

In [80]:
y_pred_proba = ann.predict(X_test)
y_pred = y_pred_proba > 0.5
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred.reshape(len(y_pred),1)), axis = 1))

[[0 0]
 [1 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


**Making the Confusion Matrix**

In [81]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [88]:
print(confusion_matrix(y_test, y_pred))

[[1521   74]
 [ 197  208]]


In [87]:
print(accuracy_score(y_test, y_pred))

0.8645


In [86]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1595
           1       0.74      0.51      0.61       405

    accuracy                           0.86      2000
   macro avg       0.81      0.73      0.76      2000
weighted avg       0.86      0.86      0.85      2000

